# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/sk/Desktop/EcoAttention/ManhattanAttention/ManhattanAttention.srcs/sources_1/bd/ManhattanAttention/ip/ManhattanAttention_axis_wrapper_0_0/ManhattanAttention_axis_wrapper_0_0.xci
# IP: The module: 'ManhattanAttention_axis_wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/sk/Desktop/EcoAttention/ManhattanAttention/ManhattanAttention.gen/sources_1/bd/ManhattanAttention/ip/ManhattanAttention_axis_wrapper_0_0/src/ADDER/ADDER.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ADDER || ORIG_REF_NAME==ADDER} -quiet] -quiet

# IP: /home/sk/Desktop/EcoAttention/ManhattanAttention/ManhattanAttention.gen/sources_1/bd/ManhattanAttention/ip/ManhattanAttention_axis_wrapper_0_0/src/EXP/EXP.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==EXP || ORIG_REF_NAME==EXP} -quiet] -quiet

# IP: /home/sk/Desktop/EcoAttention/ManhattanAttention/ManhattanAttention.gen/sources_1/bd/ManhattanAttention/ip/ManhattanAttention_axis_wrapper_0_0/src/GREATERthan/GREATERthan.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==GREATERthan || ORIG_REF_NAME==GREATERthan} -quiet] -quiet

# IP: /home/sk/Desktop/EcoAttention/ManhattanAttention/ManhattanAttention.gen/sources_1/bd/ManhattanAttention/ip/ManhattanAttention_axis_wrapper_0_0/src/MUL/MUL.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MUL || ORIG_REF_NAME==MUL} -quiet] -quiet

# IP: /home/sk/Desktop/EcoAttention/ManhattanAttention/ManhattanAttention.gen/sources_1/bd/ManhattanAttention/ip/ManhattanAttention_axis_wrapper_0_0/src/CACHE/CACHE.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CACHE || ORIG_REF_NAME==CACHE} -quiet] -quiet

# IP: /home/sk/Desktop/EcoAttention/ManhattanAttention/ManhattanAttention.gen/sources_1/bd/ManhattanAttention/ip/ManhattanAttention_axis_wrapper_0_0/src/K/K.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==K || ORIG_REF_NAME==K} -quiet] -quiet

# IP: /home/sk/Desktop/EcoAttention/ManhattanAttention/ManhattanAttention.gen/sources_1/bd/ManhattanAttention/ip/ManhattanAttention_axis_wrapper_0_0/src/O/O.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==O || ORIG_REF_NAME==O} -quiet] -quiet

# IP: /home/sk/Desktop/EcoAttention/ManhattanAttention/ManhattanAttention.gen/sources_1/bd/ManhattanAttention/ip/ManhattanAttention_axis_wrapper_0_0/src/Q/Q.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Q || ORIG_REF_NAME==Q} -quiet] -quiet

# IP: /home/sk/Desktop/EcoAttention/ManhattanAttention/ManhattanAttention.gen/sources_1/bd/ManhattanAttention/ip/ManhattanAttention_axis_wrapper_0_0/src/V/V.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==V || ORIG_REF_NAME==V} -quiet] -quiet

# XDC: /home/sk/Desktop/EcoAttention/ManhattanAttention/ManhattanAttention.gen/sources_1/bd/ManhattanAttention/ip/ManhattanAttention_axis_wrapper_0_0/src/CACHE/CACHE_ooc.xdc

# XDC: /home/sk/Desktop/EcoAttention/ManhattanAttention/ManhattanAttention.gen/sources_1/bd/ManhattanAttention/ip/ManhattanAttention_axis_wrapper_0_0/src/K/K_ooc.xdc

# XDC: /home/sk/Desktop/EcoAttention/ManhattanAttention/ManhattanAttention.gen/sources_1/bd/ManhattanAttention/ip/ManhattanAttention_axis_wrapper_0_0/src/O/O_ooc.xdc

# XDC: /home/sk/Desktop/EcoAttention/ManhattanAttention/ManhattanAttention.gen/sources_1/bd/ManhattanAttention/ip/ManhattanAttention_axis_wrapper_0_0/src/Q/Q_ooc.xdc

# XDC: /home/sk/Desktop/EcoAttention/ManhattanAttention/ManhattanAttention.gen/sources_1/bd/ManhattanAttention/ip/ManhattanAttention_axis_wrapper_0_0/src/V/V_ooc.xdc

# XDC: /home/sk/Desktop/EcoAttention/ManhattanAttention/ManhattanAttention.gen/sources_1/bd/ManhattanAttention/ip/ManhattanAttention_axis_wrapper_0_0/src/constraint.xdc
# XDC: The top module name and the constraint reference have the same name: 'ManhattanAttention_axis_wrapper_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/sk/Desktop/EcoAttention/ManhattanAttention/ManhattanAttention.srcs/sources_1/bd/ManhattanAttention/ip/ManhattanAttention_axis_wrapper_0_0/ManhattanAttention_axis_wrapper_0_0.xci
# IP: The module: 'ManhattanAttention_axis_wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/sk/Desktop/EcoAttention/ManhattanAttention/ManhattanAttention.gen/sources_1/bd/ManhattanAttention/ip/ManhattanAttention_axis_wrapper_0_0/src/ADDER/ADDER.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ADDER || ORIG_REF_NAME==ADDER} -quiet] -quiet

# IP: /home/sk/Desktop/EcoAttention/ManhattanAttention/ManhattanAttention.gen/sources_1/bd/ManhattanAttention/ip/ManhattanAttention_axis_wrapper_0_0/src/EXP/EXP.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==EXP || ORIG_REF_NAME==EXP} -quiet] -quiet

# IP: /home/sk/Desktop/EcoAttention/ManhattanAttention/ManhattanAttention.gen/sources_1/bd/ManhattanAttention/ip/ManhattanAttention_axis_wrapper_0_0/src/GREATERthan/GREATERthan.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==GREATERthan || ORIG_REF_NAME==GREATERthan} -quiet] -quiet

# IP: /home/sk/Desktop/EcoAttention/ManhattanAttention/ManhattanAttention.gen/sources_1/bd/ManhattanAttention/ip/ManhattanAttention_axis_wrapper_0_0/src/MUL/MUL.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MUL || ORIG_REF_NAME==MUL} -quiet] -quiet

# IP: /home/sk/Desktop/EcoAttention/ManhattanAttention/ManhattanAttention.gen/sources_1/bd/ManhattanAttention/ip/ManhattanAttention_axis_wrapper_0_0/src/CACHE/CACHE.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CACHE || ORIG_REF_NAME==CACHE} -quiet] -quiet

# IP: /home/sk/Desktop/EcoAttention/ManhattanAttention/ManhattanAttention.gen/sources_1/bd/ManhattanAttention/ip/ManhattanAttention_axis_wrapper_0_0/src/K/K.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==K || ORIG_REF_NAME==K} -quiet] -quiet

# IP: /home/sk/Desktop/EcoAttention/ManhattanAttention/ManhattanAttention.gen/sources_1/bd/ManhattanAttention/ip/ManhattanAttention_axis_wrapper_0_0/src/O/O.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==O || ORIG_REF_NAME==O} -quiet] -quiet

# IP: /home/sk/Desktop/EcoAttention/ManhattanAttention/ManhattanAttention.gen/sources_1/bd/ManhattanAttention/ip/ManhattanAttention_axis_wrapper_0_0/src/Q/Q.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Q || ORIG_REF_NAME==Q} -quiet] -quiet

# IP: /home/sk/Desktop/EcoAttention/ManhattanAttention/ManhattanAttention.gen/sources_1/bd/ManhattanAttention/ip/ManhattanAttention_axis_wrapper_0_0/src/V/V.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==V || ORIG_REF_NAME==V} -quiet] -quiet

# XDC: /home/sk/Desktop/EcoAttention/ManhattanAttention/ManhattanAttention.gen/sources_1/bd/ManhattanAttention/ip/ManhattanAttention_axis_wrapper_0_0/src/CACHE/CACHE_ooc.xdc

# XDC: /home/sk/Desktop/EcoAttention/ManhattanAttention/ManhattanAttention.gen/sources_1/bd/ManhattanAttention/ip/ManhattanAttention_axis_wrapper_0_0/src/K/K_ooc.xdc

# XDC: /home/sk/Desktop/EcoAttention/ManhattanAttention/ManhattanAttention.gen/sources_1/bd/ManhattanAttention/ip/ManhattanAttention_axis_wrapper_0_0/src/O/O_ooc.xdc

# XDC: /home/sk/Desktop/EcoAttention/ManhattanAttention/ManhattanAttention.gen/sources_1/bd/ManhattanAttention/ip/ManhattanAttention_axis_wrapper_0_0/src/Q/Q_ooc.xdc

# XDC: /home/sk/Desktop/EcoAttention/ManhattanAttention/ManhattanAttention.gen/sources_1/bd/ManhattanAttention/ip/ManhattanAttention_axis_wrapper_0_0/src/V/V_ooc.xdc

# XDC: /home/sk/Desktop/EcoAttention/ManhattanAttention/ManhattanAttention.gen/sources_1/bd/ManhattanAttention/ip/ManhattanAttention_axis_wrapper_0_0/src/constraint.xdc
# XDC: The top module name and the constraint reference have the same name: 'ManhattanAttention_axis_wrapper_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
