# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/sk/Desktop/EcoAttention/ManhattanAttention/ManhattanAttention.srcs/sources_1/bd/ManhattanAttention/ip/ManhattanAttention_zynq_ultra_ps_e_0_0/ManhattanAttention_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'ManhattanAttention_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sk/Desktop/EcoAttention/ManhattanAttention/ManhattanAttention.gen/sources_1/bd/ManhattanAttention/ip/ManhattanAttention_zynq_ultra_ps_e_0_0/ManhattanAttention_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ManhattanAttention_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/sk/Desktop/EcoAttention/ManhattanAttention/ManhattanAttention.gen/sources_1/bd/ManhattanAttention/ip/ManhattanAttention_zynq_ultra_ps_e_0_0/ManhattanAttention_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ManhattanAttention_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/sk/Desktop/EcoAttention/ManhattanAttention/ManhattanAttention.srcs/sources_1/bd/ManhattanAttention/ip/ManhattanAttention_zynq_ultra_ps_e_0_0/ManhattanAttention_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'ManhattanAttention_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sk/Desktop/EcoAttention/ManhattanAttention/ManhattanAttention.gen/sources_1/bd/ManhattanAttention/ip/ManhattanAttention_zynq_ultra_ps_e_0_0/ManhattanAttention_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ManhattanAttention_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/sk/Desktop/EcoAttention/ManhattanAttention/ManhattanAttention.gen/sources_1/bd/ManhattanAttention/ip/ManhattanAttention_zynq_ultra_ps_e_0_0/ManhattanAttention_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ManhattanAttention_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
