# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/ManhattanAttention/ManhattanAttention.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ManhattanAttention || ORIG_REF_NAME==ManhattanAttention} -quiet] -quiet

# IP: bd/ManhattanAttention/ip/ManhattanAttention_zynq_ultra_ps_e_0_0/ManhattanAttention_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ManhattanAttention_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==ManhattanAttention_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/ManhattanAttention/ip/ManhattanAttention_axis_wrapper_0_0/ManhattanAttention_axis_wrapper_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ManhattanAttention_axis_wrapper_0_0 || ORIG_REF_NAME==ManhattanAttention_axis_wrapper_0_0} -quiet] -quiet

# IP: bd/ManhattanAttention/ip/ManhattanAttention_axi_dma_0_0/ManhattanAttention_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ManhattanAttention_axi_dma_0_0 || ORIG_REF_NAME==ManhattanAttention_axi_dma_0_0} -quiet] -quiet

# IP: bd/ManhattanAttention/ip/ManhattanAttention_ps8_0_axi_periph_0/ManhattanAttention_ps8_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ManhattanAttention_ps8_0_axi_periph_0 || ORIG_REF_NAME==ManhattanAttention_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/ManhattanAttention/ip/ManhattanAttention_rst_ps8_0_100M_0/ManhattanAttention_rst_ps8_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ManhattanAttention_rst_ps8_0_100M_0 || ORIG_REF_NAME==ManhattanAttention_rst_ps8_0_100M_0} -quiet] -quiet

# IP: bd/ManhattanAttention/ip/ManhattanAttention_axi_smc_0/ManhattanAttention_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ManhattanAttention_axi_smc_0 || ORIG_REF_NAME==ManhattanAttention_axi_smc_0} -quiet] -quiet

# IP: bd/ManhattanAttention/ip/ManhattanAttention_auto_ds_0/ManhattanAttention_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ManhattanAttention_auto_ds_0 || ORIG_REF_NAME==ManhattanAttention_auto_ds_0} -quiet] -quiet

# IP: bd/ManhattanAttention/ip/ManhattanAttention_auto_pc_0/ManhattanAttention_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ManhattanAttention_auto_pc_0 || ORIG_REF_NAME==ManhattanAttention_auto_pc_0} -quiet] -quiet

# XDC: /home/sk/Desktop/EcoAttention/ManhattanAttention/ManhattanAttention.gen/sources_1/bd/ManhattanAttention/ManhattanAttention_ooc.xdc
