#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2023.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Aug 05 19:19:34 IST 2025
# SW Build 3865809 on Sun May  7 15:04:56 MDT 2023
#
# IP Build 3864474 on Sun May  7 20:36:21 MDT 2023
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim fp16tb_behav -key {Behavioral:sim_1:Functional:fp16tb} -tclbatch fp16tb.tcl -view /home/dell/Desktop/projects/RISCVextension/EcoAttention/fp16tb_behav.wcfg -log simulate.log"
xsim fp16tb_behav -key {Behavioral:sim_1:Functional:fp16tb} -tclbatch fp16tb.tcl -view /home/dell/Desktop/projects/RISCVextension/EcoAttention/fp16tb_behav.wcfg -log simulate.log

