# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/sk/EXP/EXP.srcs/sources_1/ip/MAC/MAC.xci
# IP: The module: 'MAC' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sk/EXP/EXP.gen/sources_1/ip/MAC/MAC_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MAC'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/sk/EXP/EXP.srcs/sources_1/ip/MAC/MAC.xci
# IP: The module: 'MAC' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sk/EXP/EXP.gen/sources_1/ip/MAC/MAC_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MAC'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
